### PR TITLE
2016 01 12 onsite email updates

### PR DESCRIPTION
**Pull request by cowperthwait**
for @kaseybyrne 

todo after Kasey tweaks copy:
- [x] re-break lines at 80 col
- [x] replace tabs with spaces

### CODE REVIEW

**Comment by cowperthwait** [comment]
@nexdrew @bcoe 

Here’s marketing’s pass at a revision. Your thoughts?

**Comment by nexdrew** [comment]
LGTM :+1:

**Comment by cowperthwait** [comment]
Cleared on the marketing end; feel free to merge if it passes whatever editorial checklist exists on your end.

**Comment by ashleygwilliams** [comment]
wfm. lemme know if you want help rebasing into a single commit :wink:

**Comment by cowperthwait** [comment]
@ashleygwilliams: rebased 🎉

**Comment by ashleygwilliams** [comment]
hey! nice squash. i'm concerned the tests aren't passing though. 

basically the tests take data and insert it into the template, then check to see that that data is there. turns out that since the template was changed, something doesn't work!

the test is: https://github.com/npm/email-templates/blob/master/test/enterprise-verification.js#L17-L30
you can run the tests locally on your machine by running `npm test` in the root of the directory
you can read the results of the travis test here: https://travis-ci.org/npm/email-templates/jobs/101990758

lemme know if you wanna try this on your own, or i can pair with ya :)

**Comment by cowperthwait** [comment]
in re 
>All checks have failed

please advise if there are next steps required on my end to fix this

**Comment by cowperthwait** [comment]
Tests passed; back to you @nexdrew & @bcoe

**Comment by ashleygwilliams** [comment]
since your so good at it @cowperthwait you should maybe squash :wink:

**Comment by nexdrew** [comment]
Here's a Gmail preview. Looks like the unicode hearts may not render in all email clients.

gmail

**Comment by cowperthwait** [comment]
>Looks like the unicode hearts may not render in all email clients
ah balls

Ok, rather than trying to figure out how to send proper encoding in the message headers, it likely makes sense just to take these out, yes?

**Comment by nexdrew** [comment]
I think so, yes. Others may think differently.

**Pull request merged**
