### PR TITLE
Replace {{from}} with {{fromEmail}}

### LINKED ISSUE #18: Fix "from" in meta template expansion to use a non-nodemailer var name
Currently the meta templates contain JSON similar to:

```json
{
  "subject": "Your npm On-Site trial license key and instructions",
  "to": "\"{{name}}\" <{{email}}>",
  "from": "\"npm, Inc.\" <{{from}}>"
}
```

But doing `"from": "\"npm, Inc.\" <{{from}}>"` is problematic because the data given to expand `{{from}}` _will overwrite_ the `"from"` meta field entirely instead of expanding it. This is self-defeating, rendering the `"from"` meta field useless.

The result of this problem is that all emails will only use the address `{{from}}` (e.g. `website@npmjs.com`) instead of the desired format `"npm, Inc." <{{from}}>` (e.g. `npm, Inc. <website@npmjs.com>`), as evidenced by emails sent from npm/newww.

To fix, we can simply change the template variable `{{from}}` to something unique (i.e. not expected by nodemailer) like `{{fromEmail}}`. This change can be made without affecting existing functionality of npm/newww since the [data it gives](https://github.com/npm/newww/blob/v4.0.1/services/email/methods/send.js#L10) overwrites the `"from"` meta field anyway. The meta templates in this module should change first, then the field name provided by npm/newww can change to complete the fix.

### PR DESCRIPTION
**Pull request by nexdrew**
Fixes #18, see description there.

This change probably constitutes a major version bump, even though expanding `{{from}}` inside a `"from"` field probably never worked (at least not with `mustache-mailer`).

As noted in the issue, this can be safely merged and released without breaking npm/newww, since the `from` field in newww's email sending logic is already "broken" (not working as intended).

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
:+1: i like this change

when i receive emails from npm's website, they looked like this, which is confusing and not terribly professional looking:
screenshot 2015-12-30 at 12 49 59 pm

**Comment by ashleygwilliams** [comment]
two things:

1. looks like there aren't tests, but might be better late than never?
2. maybe take the word "self-defeating" out of the title as it doesn't add much value and might be a little mean?

**Comment by nexdrew** [comment]
I used "self-defeating" b/c it describes why the change is even needed. But in the spirit of NVC, I will remove it.

**Comment by nexdrew** [comment]
After adding some tests, I found the root of the problem is in the [order of property overrides](https://github.com/npm/mustache-mailer/blob/v2.1.2/index.js#L37) in `mustache-mailer` (notice that `data` overrides `meta`). Therefore, I'm opting for the simpler solution of modifying it instead of modifying `email-templates` and `newww`.

I will close this and open another PR to add some simple template expansion tests.

**Pull request closed without merging**
